### ISSUE TITLE
Tidy up code to set OCP version annotation

### ISSUE THREAD

**Issue by mmulholla** [redhat-certification/chart-verifier#146]
This PR https://github.com/redhat-certification/chart-verifier/pull/133 moved the code to get the OCP Version into the chart-testing check and uses the ChartOptions to enable setting of the annotation. Both of these are not ideal. Possible solution:

1. Make a new check which is to get the OCP Version
2. Provide a mechanism to enable a check to set a value for an annotation.

**Comment by isutton** [comment]
> This PR https://github.com/redhat-certification/chart-verifier/pull/133 moved the code to get the OCP Version into the chart-testing check and uses the ChartOptions to enable setting of the annotation. Both of these are not ideal. Possible solution:
>
> 1. Make a new check which is to get the OCP Version
> 2. Provide a mechanism to enable a check to set a value for an annotation.  

I would invert this order, since first we need to understand how do we
(if we need to) propagate collected check data into the report and once
this is defined, the glue should be straight-forward.

Some approaches to be considered:

1. Modify the CheckFunc definition to include the bag of collected
values as a map[string]string return value.

       type CheckFunc func(options *CheckOptions) (Result, map[string]string, error)

2. Modify the Result definition to include the bag of collected values
as a map[string]string field.

        type Result struct {
                // Ok indicates whether the result was successful or not.
                Ok bool
                // Reason for the result value.  This is a message indicating
                // the reason for the value of Ok became true or false.
                Reason string
                // CollectedValues contains information the check
                // developer decided to propagate to the report as
                // interesting information.
                CollectedValues map[string]string
        }


3. Modify the CheckFunc to accept, outside of CheckOptions, an
AnnotationHolder value that can be used to contribute values to the
annotation--although I'd rename it to AnnotationBuilder, and swap its
semantics to a builder. This builder could then be used by the Report
Builder when finalizing the process.

       type CheckFunc func(
            annSetter AnnotationSetter,
            options *CheckOptions,
       ) (Result, error)

reportBuilder could then be modified to contain an AnnotationSetter (as
the check might not require all methods of an AnnotationHolder):

        type AnnotationSetter interface {
                SetAnnotation(key, value string)
        }

        type ReportBuilder interface {
                AnnotationSetter
                SetToolVersion(name string) ReportBuilder
                SetChartUri(name string) ReportBuilder
                AddCheck(name string, checkType checks.CheckType, result checks.Result) ReportBuilder
                SetChart(chart *helmchart.Chart) ReportBuilder
                SetCertifiedOpenShiftVersion(version string) ReportBuilder
                Build() (*Report, error)
        }

        func (r *reportBuilder) SetAnnotation(key, value string) {
                r.Report.SetAnnotation(key, value)
        }

The check could then interact with the AnnotationSetter interface
without requiring access to the annotation holder.

**Comment by mmulholla** [comment]
Option 3 looks the best to me. Thanks
