### ISSUE TITLE
Why did the latest release go backwards in time?

### ISSUE THREAD

**Issue by acornett21** [redhat-certification/chart-verifier#308]
It seems that the latest release `0.1.0` went backwards in time. Should the latest release be `1.9.1` or `1.10.0`?

**Comment by komish** [comment]
@mmulholla this issue refers to release 0.1.0 https://github.com/redhat-certification/chart-verifier/releases/tag/0.1.0 - to my eye, this release looks like it was a workflow test that accidentally published a release, or published a release but didn't mark it as a pre-release?

If the release was accidental, resolution here would probably just be **deleting that release** and then **closing this issue as resolved**.

**Comment by mmulholla** [comment]
@komish 0.1.0 release is created on every merge into the repository and represents the latest version from the main branch. When release 1.10.0 was created the merge of the release file into the repo caused a new 0.1.0 image to be created and at the time will be the same as 1.10.0. 

This is the workflow which created the 0.1.0 release: https://github.com/redhat-certification/chart-verifier/blob/main/.github/workflows/dev_release.yaml

The reason we create this is because the chart-verifier redhat action requires the chart verifier version to be set using a valid semantic version, and so outrtest workflows all use image 0.1.0.

**Comment by komish** [comment]
@mmulholla I'm not certain I'm following yet. Few more questions -

I pulled the 0.1.0 that's listed as being created 2023-01-26. The referenced commit is here https://github.com/redhat-certification/chart-verifier/commit/bab70e0049a90a960bb0aaa0f327996d8685f038

If I pull that tarball in the artifacts, I get the chart-verifier binary, but it shows 1.9.0 as the version.

```
 ⤿ chart-verifier-0.1.0/chart-verifier version
v1.9.0
```

Pulling the one from the 1.10.0 release does show the right value (which is what I expect)

```
 ⤿ chart-verifier-1.10.0/chart-verifier version
v1.10.0
```

When you say that the test workflows use image 0.1.0, I'm assuming that's so that they can always use the very last thing merged into main, vs. a release? I'm not certain where the semantic version requirement is coming into play here. Wouldn't the redhat-actions want to always use whatever the latest version is?

**Comment by komish** [comment]
Closing this issue. We've got a bit of a better understanding of this now. There's a potential opportunity for improvement but we'll add that to a future roadmap.
